//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sali
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int enrollment_id { get; set; }
        public int member_id { get; set; }
        public int class_id { get; set; }
        public Nullable<System.DateTime> enrollment_date { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Class Class1 { get; set; }
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
    }
}
