//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sali
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_Rentals
    {
        public int rental_id { get; set; }
        public int member_id { get; set; }
        public int equipment_id { get; set; }
        public System.DateTime rental_date { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
        public string rental_status { get; set; }
        public string notes { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Member Member { get; set; }
    }
}
