//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sali
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int visit_id { get; set; }
        public int member_id { get; set; }
        public Nullable<System.DateTime> visit_date { get; set; }
        public Nullable<System.TimeSpan> check_in_time { get; set; }
        public Nullable<System.TimeSpan> check_out_time { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
